import numpy as np
import pandas as pd
from volatilitystats.utils.confidence import compute_confidence_bands as compute_confidence_bands

def garch_in_mean_log_likelihood(params: np.ndarray, returns: pd.Series, p: int, q: int) -> float: ...
def estimate_garch_in_mean_params(returns: pd.Series, p: int = 1, q: int = 1, with_confidence: bool = False, stderr_fraction: float = 0.1) -> dict: ...
