import pandas as pd
from typing import Sequence
from volatilitystats.utils.confidence import compute_confidence_bands as compute_confidence_bands

def harch_log_likelihood(params: Sequence[float], returns: pd.Series, lags: Sequence[int]) -> float: ...
def estimate_harch_params(returns: pd.Series, lags: Sequence[int], with_confidence: bool = False, stderr_fraction: float = 0.1) -> dict: ...
