import numpy as np
import pandas as pd

def barndorff_nielsen_shephard_jump_test(returns: np.ndarray | pd.Series, threshold: float = 4.0) -> bool: ...
def detect_jumps_series(df: pd.DataFrame, price_column: str, time_column: str, freq: str = '1D', threshold: float = 4.0) -> pd.Series: ...
