import numpy as np
import pandas as pd

def median_realized_volatility(returns: np.ndarray | pd.Series) -> float: ...
def median_rv_series(df: pd.DataFrame, price_column: str, time_column: str, freq: str = '1D') -> pd.Series: ...
