import numpy as np
import pandas as pd

def realized_kernel(returns: np.ndarray | pd.Series, kernel: str = 'bartlett', bandwidth: int = None) -> float: ...
def kernel_weight(h: int, bandwidth: int, kernel: str) -> float: ...
def realized_kernel_series(df: pd.DataFrame, price_column: str, time_column: str, freq: str = '1D', kernel: str = 'bartlett', bandwidth: int = None) -> pd.Series: ...
