import numpy as np
import pandas as pd

def bipower_variation(returns: np.ndarray | pd.Series) -> float: ...
def bipower_variation_series(df: pd.DataFrame, price_column: str, time_column: str, freq: str = '1D') -> pd.Series: ...
