import pandas as pd
from typing import Sequence

def egarch_log_likelihood(params: Sequence[float], returns: pd.Series, p: int, q: int) -> float: ...
def estimate_egarch_params(returns: pd.Series, p: int = 1, q: int = 1) -> dict: ...
