import numpy as np
import pandas as pd

def garch_in_mean_log_likelihood(params: np.ndarray, returns: pd.Series, p: int, q: int) -> float: ...
def estimate_garch_in_mean_params(returns: pd.Series, p: int = 1, q: int = 1) -> dict: ...
