import pandas as pd
from typing import Sequence

def gjr_garch_log_likelihood(params: Sequence[float], returns: pd.Series, p: int, q: int) -> float: ...
def estimate_gjr_garch_params(returns: pd.Series, p: int = 1, q: int = 1) -> dict: ...
