import pandas as pd
from typing import Sequence

def harch_log_likelihood(params: Sequence[float], returns: pd.Series, lags: Sequence[int]) -> float: ...
def estimate_harch_params(returns: pd.Series, lags: Sequence[int]) -> dict: ...
